dist: focal

language: php

php:
  - '7.4'

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.travis .env
  - sudo mysql -e 'CREATE DATABASE testing;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --no-interaction -vvv
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - nvm install --lts
  - npm install npm@latest -g
  - npm install -g jshint
  - npm install

script:
  - vendor/bin/phpunit --coverage-text
  #- phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
  #- npm run production
  #- jshint resources/assets/js/modules/*
